MODEL:
  VID:
    METHOD: "mega"
    ROI_BOX_HEAD:
      ATTENTION:
        ENABLE: True
        STAGE: 3
  META_ARCHITECTURE: "GeneralizedRCNNMEGA"
  WEIGHT: "/home/hongwei/video-object-detection/mega.pytorch/ckpts/MEGA_R_101.pth"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "MEGAFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("HAKE_train",)
  TEST: ("HAKE_val",)